/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cart: typeof import('./src/components/icon/Cart.vue')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductCart: typeof import('./src/components/ProductCart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
